export const DEFAULTS = {
  // Commensal parameters
  INITIAL_COMMENSAL_SPECIES_COUNT: 12,
  COMMENSAL_TOTAL_CAPACITY: 1.0,
  COMMENSAL_BASE_GROWTH_RATE: 0.18,
  COMMENSAL_ANTIBIOTIC_KILL_RATE: 0.9,

  // C. diff parameters
  INITIAL_CDIFF_SPORES: 0.05,
  INITIAL_CDIFF_VEGETATIVE: 0.0,
  CDIFF_SPORE_GERMINATION_BASE: 0.01,
  CDIFF_SPORE_GERMINATION_EMPTY: 0.40,
  CDIFF_ANTIBIOTIC_KILL_VEGETATIVE: 0.8,
  CDIFF_ANTIBIOTIC_KILL_SPORES: 0.0,
  CDIFF_TOXIN_DECAY_RATE: 0.10,
  CDIFF_SPORULATION_RATE: 0.05,

  // C. diff virulence (1-10 scale, default 5)
  // Maps to growth rate and toxin production via linear interpolation
  CDIFF_DEFAULT_VIRULENCE: 5,
  CDIFF_GROWTH_RATE_MIN: 0.05,   // virulence 1
  CDIFF_GROWTH_RATE_MAX: 0.45,   // virulence 10
  CDIFF_TOXIN_RATE_MIN: 0.05,    // virulence 1
  CDIFF_TOXIN_RATE_MAX: 0.35,    // virulence 10

  // Competitive exclusion
  COMPETITIVE_EXCLUSION_THRESHOLD: 0.3,
  COMPETITIVE_EXCLUSION_STRENGTH: 1.0,

  // Antibiotic course
  ANTIBIOTIC_COURSE_DURATION: 10,

  // Therapeutic (SER-109/Vowst-like)
  THERAPEUTIC_COMMENSAL_BOOST: 0.65,
  THERAPEUTIC_SPECIES_ADDED: 8,
  THERAPEUTIC_ENGRAFTMENT_BONUS: 0.12,

  // Health score
  HEALTH_BASELINE: 100,
  HEALTH_TOXIN_DAMAGE_RATE: 30,
  HEALTH_RECOVERY_RATE: 2,

  // Recurrence detection
  RECURRENCE_THRESHOLD: 0.3,

  // Outcome thresholds
  MAX_SIMULATION_TICKS: 200,

  // Randomization variance
  GROWTH_RATE_VARIANCE: 0.03,
  SENSITIVITY_VARIANCE: 0.15,
} as const
